export enum LoanStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  REPAYING = 'REPAYING',
  REPAID = 'REPAID',
  DEFAULTED = 'DEFAULTED',
}
